=== bassclefstudio/DocLang/DocLang/Xml/Base-v1.xsd
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    xmlns="http://bassclefstudio.dev/DocLang/v1/Base"
    targetNamespace="http://bassclefstudio.dev/DocLang/v1/Base">
    <xs:element name="Document" type="Document">
    </xs:element>

    <xs:complexType name="Document">
        <xs:annotation>
            <xs:documentation>A representation of a full document written in DocLang.</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="Title" type="Content">
                <xs:annotation>
                    <xs:documentation>The title of the document, as displayed in the document itself.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Authors" type="Authors">
                <xs:annotation>
                    <xs:documentation>A person involved in the creation or publication of a document.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Content" type="Content">
                <xs:annotation>
                    <xs:documentation>The contents of this document.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="Id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>A unique ID in the document tree that identifies this document.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="Name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The name of the document which is shown externally.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Content" mixed="true">
        <xs:annotation>
            <xs:documentation>Represents a collection of Node objects, interspersed optionally with text content, that can be written into a DocLang document body.</xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Paragraph" type="Paragraph">
                <xs:annotation>
                    <xs:documentation>Contains a paragraph containing some other document content.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Heading" type="Heading">
                <xs:annotation>
                    <xs:documentation>Defines a heading containing some other document content.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="List" type="List">
                <xs:annotation>
                    <xs:documentation>Defines a list containing a collection of document content.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Bold" type="Bold">
                <xs:annotation>
                    <xs:documentation>Formats some document content in bold.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Italic" type="Italic">
                <xs:annotation>
                    <xs:documentation>Formats some document content in italics.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Math" type="Math">
                <xs:annotation>
                    <xs:documentation>Formats and stores document content representing mathematical expressions.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Code" type="Code">
                <xs:annotation>
                    <xs:documentation>Formats document content describing a code snippet in some programming language.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Extension" type="Extension">
                <xs:annotation>
                    <xs:documentation>Provides extended output content for specific output document types (such as additional HTML for web conversion, or additional content when outputting Markdown).</xs:documentation>
                </xs:annotation>
           </xs:element>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Heading">
        <xs:annotation>
            <xs:documentation>A logical, named grouping of content within a document.</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="Title" type="Content">
                <xs:annotation>
                    <xs:documentation>The title of the heading, as displayed in the document itself.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Content" type="Content">
                <xs:annotation>
                    <xs:documentation>The contents of this heading.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="Id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>A unique ID in the document tree that identifies this heading.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="Name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The name of the heading which is shown externally.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="List">
        <xs:annotation>
            <xs:documentation>A logical structure of list items (ordered or unordered), each containing their own content.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Item" type="Content" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>The contents of an individual item within the list.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="Type" type="ListType" use="required">
            <xs:annotation>
                <xs:documentation>The type of list which should be rendered. This also determines the importance of order in the child Items.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="ListType">
        <xs:annotation>
            <xs:documentation>A description of the type of list content that is being presented.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Numerical">
                <xs:annotation>
                    <xs:documentation>A numbered list, which counts items in the order presented.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Bulleted">
                <xs:annotation>
                    <xs:documentation>An unordered list where each item is indicated by a 'bullet' (or identical symbol) which indicates its importance.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="None">
                <xs:annotation>
                    <xs:documentation>Content items are presented one after the other with no heading, and are separated for purely semantic reasons.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Authors">
        <xs:annotation>
            <xs:documentation>A collection of Author objects associated with a given node.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Author" type="Author" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>One of the authors associated with the work.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Author">
        <xs:annotation>
            <xs:documentation>A representation of a person who contributed to part of a DocLang document.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:annotation>
                    <xs:documentation>The author's name.</xs:documentation>
                </xs:annotation>
                <xs:attribute type="AuthorType" name="Type" use="required">
                    <xs:annotation>
                        <xs:documentation>The status/position of this author relative to the document.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="AuthorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Creator">
                <xs:annotation>
                    <xs:documentation>This author created this DocLang document, and/or was the primary contributor.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Contributor">
                <xs:annotation>
                    <xs:documentation>This author aided in the creation/writing of this DocLang document.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Editor">
                <xs:annotation>
                    <xs:documentation>This author helped proofread, edit, or otherwise revise the final document.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Publisher">
                <xs:annotation>
                    <xs:documentation>This author is responsible for publishing the completed document.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Paragraph">
        <xs:annotation>
            <xs:documentation>Represents an offset paragraph containing some content.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:annotation>
                <xs:documentation>The content within this paragraph.</xs:documentation>
            </xs:annotation>
            <xs:extension base="Content"></xs:extension>
        </xs:complexContent>      
    </xs:complexType>

    <xs:complexType name="Bold">
        <xs:annotation>
            <xs:documentation>Formats the child content in bold.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:annotation>
                <xs:documentation>The content within this formatting element.</xs:documentation>
            </xs:annotation>
            <xs:extension base="Content"></xs:extension>
        </xs:complexContent>      
    </xs:complexType>

    <xs:complexType name="Italic">
        <xs:annotation>
            <xs:documentation>Formats the child content in italics.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:annotation>
                <xs:documentation>The content within this formatting element.</xs:documentation>
            </xs:annotation>
            <xs:extension base="Content"></xs:extension>
        </xs:complexContent>      
    </xs:complexType>

    <xs:complexType name="Extension">
        <xs:annotation>
            <xs:documentation>Provides some child content which can be added to the DocLang document during certain transformation operations.</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="Content" type="xs:anyType">
                <xs:annotation>
                    <xs:documentation>The output content to append when converting this DocLang document.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="Type" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The type of document that this extension content applies to.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Math" mixed="true">
        <xs:annotation>
            <xs:documentation>Represents a tree of expressions and content representing some mathematical construct.</xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Paragraph" type="Paragraph">
                <xs:annotation>
                    <xs:documentation>Contains a paragraph containing some other document content.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Heading" type="Heading">
                <xs:annotation>
                    <xs:documentation>Defines a heading containing some other document content.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="Code">
        <xs:annotation>
            <xs:documentation>Defines code in a given programming language (escaped from XML).</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"></xs:restriction>
    </xs:simpleType>
</xs:schema>

=== bassclefstudio/DocLang/Samples/pages/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document 
    xmlns="http://bassclefstudio.dev/DocLang/v1/Base"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://bassclefstudio.dev/DocLang/v1/Base ../../DocLang/Xml/Base-v1.xsd"
    Name="Test Document"
    Id="testDoc"
    Date="2022-04-17T00:00:00Z">
    <Title>My Test Document</Title>
    <Authors>
        <Author Type="Creator">bassclefstudio</Author>
    </Authors>
    <Content>
        <Heading Name="Heading 1" Id="h1">
            <Title>First Heading (Result = ${result})</Title>
            <Content>
                <Paragraph><Bold>Lorem ipsum dolor sit amet, consectetur adipiscing elit,</Bold> sed do eiusmod tempor incididunt <Italic>ut labore et dolore magna aliqua.</Italic> A diam maecenas sed enim ut sem. Integer quis auctor elit sed vulputate mi sit. Vitae justo eget magna fermentum. Malesuada pellentesque elit eget gravida cum. Nunc scelerisque viverra mauris in. Pretium aenean pharetra magna ac placerat vestibulum. Vel eros donec ac odio tempor orci dapibus. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Pharetra sit amet aliquam id. Nibh sed pulvinar proin gravida hendrerit. Pellentesque eu tincidunt tortor aliquam nulla facilisi.</Paragraph>
                <Paragraph>Lobortis scelerisque fermentum dui faucibus in ornare quam. Vitae auctor eu augue ut lectus arcu bibendum at. Egestas maecenas pharetra convallis posuere morbi leo urna. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. At auctor urna nunc id cursus. Consectetur a erat nam at. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Luctus venenatis lectus magna fringilla. Mattis pellentesque id nibh tortor id aliquet lectus proin. Interdum velit laoreet id donec. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Mattis vulputate enim nulla aliquet porttitor. Facilisis sed odio morbi quis. Ut tristique et egestas quis ipsum suspendisse. Maecenas accumsan lacus vel facilisis. Eu ultrices vitae auctor eu augue. Et tortor consequat id porta nibh venenatis cras. Aliquam ultrices sagittis orci a scelerisque purus semper.</Paragraph>
                <Paragraph>Vitae semper quis lectus nulla at volutpat diam ut. Faucibus in ornare quam viverra orci sagittis eu. Congue eu consequat ac felis donec et odio pellentesque. Suspendisse in est ante in nibh mauris cursus mattis molestie. In dictum non consectetur a erat nam at lectus urna. In vitae turpis massa sed. Nulla facilisi cras fermentum odio eu feugiat. Eu turpis egestas pretium aenean pharetra magna ac. In vitae turpis massa sed elementum tempus egestas sed sed. Sed euismod nisi porta lorem mollis. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Maecenas pharetra convallis posuere morbi leo urna molestie. Vitae tortor condimentum lacinia quis. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Massa enim nec dui nunc mattis enim. Est pellentesque elit ullamcorper dignissim cras. Ut sem nulla pharetra diam sit amet nisl suscipit.</Paragraph>                
                <Paragraph>Mi in nulla posuere sollicitudin aliquam. Semper eget duis at tellus at urna condimentum mattis pellentesque. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Gravida neque convallis a cras semper auctor. Ut morbi tincidunt augue interdum. Donec enim diam vulputate ut pharetra sit amet. Sed vulputate mi sit amet mauris commodo. Vel eros donec ac odio tempor orci dapibus ultrices. Nisi vitae suscipit tellus mauris a diam maecenas sed. Sed libero enim sed faucibus turpis. Pharetra pharetra massa massa ultricies mi. Amet nulla facilisi morbi tempus.</Paragraph>
                <Paragraph>Et ultrices neque ornare aenean euismod elementum nisi. Netus et malesuada fames ac turpis egestas. Ante in nibh mauris cursus mattis molestie a iaculis. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Interdum velit euismod in pellentesque massa. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Volutpat ac tincidunt vitae semper quis. Ullamcorper malesuada proin libero nunc consequat. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Ut placerat orci nulla pellentesque dignissim. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Donec massa sapien faucibus et molestie ac feugiat sed lectus. Enim ut tellus elementum sagittis vitae et leo duis. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu.</Paragraph>
                <Heading Id="h2" Name="Subheading 1">
                    <Title>Second Heading</Title>
                    <Content>
                        <Paragraph>And this after the second heading, which is on level 2.</Paragraph>
                        <Paragraph>
                            <List Type="Numerical">
                                <Item>This is a numerical list of items!</Item>
                                <Item>Each one counts up from the first item to indicate their order.</Item>
                                <Item>
                                    <List Type="Bulleted">
                                        <Item>You can also nest lists if you like, to provide even more organization!</Item>
                                        <Item>Lists are first-class items just like headings and other content blocks.</Item>
                                    </List>
                                </Item>
                            </List>
                        </Paragraph>
                    </Content>
                </Heading>
            </Content>
        </Heading>
    </Content>
</Document>
